### ISSUE TITLE
could not find sample asset

### ISSUE THREAD

**Issue by hietwll** [qiutanguu/flower-engine#1]
hi qiutang,

nice project for vulkan beginners! i've run you project but failed to find the asset for your engine, i.e. the .flower file. is there any plan to make them public?

best regards!

**Comment by qiutanguu** [comment]
sure, current code polishing is wip, maybe i can release the clean engine at June, and current some asset is no under mit license, so i not push here, as an alternative, i will make some free asset for sample scene and push at that time.

**Comment by hietwll** [comment]
great, look forward to the coming release.
